### ISSUE TITLE
这只 Probe 看起来好眼熟啊...

### ISSUE THREAD

**Issue by ProtossProbe** [LePtC/ProbeSim#1]
给萌狸大大跪了。教练，Probe 也想学游戏开发😂

另外发现 [Duckers](http://store.steampowered.com/app/254320/) 这个游戏里居然出现了 Probe X Drone 这种异常冷门的cp，好感动...（大雾

**Comment by LePtC** [comment]
有没有兴趣做 Duskers 的实况啊，我想看 (｀･ω･´)

**Comment by ProtossProbe** [comment]
@LePtC 我先把UT的大坑填完再来看看这个游戏...

**Comment by ProtossProbe** [comment]
关于音效...既然是 Probe 模拟器，用 Probe 本来的音效会比较好？？（但是不知道会不会和暴雪爸爸牵扯到版权问题...）

我把星际一和星际二的 Probe 音效都传了一份...如果有需要的话：
https://drive.google.com/open?id=0BzO5X3PwWFHpd1VibmpjLTQ3VjA
https://drive.google.com/open?id=0BzO5X3PwWFHpeV9yQm9zYWVEbnc

**Comment by LePtC** [comment]
@ProtossProbe 好的我会试试（其实现在用的这个音效是 Duskers 的音效，只不过 javascript 播放出来的效果比较恼火）

**Comment by LePtC** [comment]
@ProtossProbe  我正在想 Probe2 的名字… 你名字里的 Protoss 是什么意思丫？

**Comment by ProtossProbe** [comment]
@LePtC Protoss 是种族名称，国服翻译成“星灵”。

**Comment by LePtC** [comment]
@ProtossProbe （一脸懵逼）还是就叫 Probe2 吧…
